
services:
  mongodb:
    image: mongo:5.0
    container_name: location-mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: locationdb
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data: