services:
  mongo:
    image: mongo:latest
    container_name: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME={MONGO_ROOT_USERNAME:-root}
      - MONGO_INITDB_ROOT_PASSWORD={MONGO_ROOT_PASSWORD}
      - MONGO_INITDB_DATABASE=locationdb
    volumes:
      - mongodb_data:/data/db
    ports:
      - "27017:27017"
    networks:
      - packagenet
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5

  mongo-express:
    image: mongo-express:latest
    container_name: mongo-express
    depends_on:
      mongo:
        condition: service_healthy
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongo
      - ME_CONFIG_MONGODB_ADMINUSERNAME={MONGO_ROOT_USERNAME:-root}
      - ME_CONFIG_MONGODB_ADMINPASSWORD={MONGO_ROOT_PASSWORD}
      - ME_CONFIG_BASICAUTH_USERNAME={MONGO_EXPRESS_USERNAME:-admin}
      - ME_CONFIG_BASICAUTH_PASSWORD={MONGO_EXPRESS_PASSWORD}
      - ME_CONFIG_MONGODB_ENABLE_ADMIN=true
    ports:
      - "8084:8081"
    networks:
      - packagenet

  location-service-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: location-service-app
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://${MONGO_ROOT_USERNAME:-root}:${MONGO_ROOT_PASSWORD}@mongo:27017/locationdb?authSource=admin
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=${EUREKA_URL:-http://eureka-server:8761/eureka/}
      - SPRING_PROFILES_ACTIVE=docker
    ports:
      - "8090:8090"
    depends_on:
      mongo:
        condition: service_healthy
    restart: on-failure
    networks:
      - packagenet

networks:
  packagenet:
    name: packagenet
    driver: bridge
    external: true

volumes:
  mongodb_data:
