spring.application.name=LOCATION-SERVICE
server.port=8090
spring.data.mongodb.host=localhost
spring.data.mongodb.port=27017
spring.data.mongodb.database=locationdb
spring.data.mongodb.username=root
spring.data.mongodb.password=mongopass
spring.data.mongodb.authentication-database=admin
eureka.client.enabled=true
eureka.client.service-url.defaultZone=http://localhost:8761/eureka
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
resilience4j.circuitbreaker.instances.packageService.failure-rate-threshold=50
resilience4j.circuitbreaker.instances.packageService.wait-duration-in-open-state=10000
resilience4j.circuitbreaker.instances.packageService.sliding-window-size=10
resilience4j.retry.instances.packageService.max-attempts=3
resilience4j.retry.instances.packageService.wait-duration=1000

